### ISSUE TITLE
QA checklist

### ISSUE THREAD

**Issue by XXIX** [parsons/parsons-mps#10]
General
- [x] Hyperlinks work and lead to the desired result
- [x] CTAs work and lead to the desired result
- [x] Non-client-side text doesn’t have spelling and grammar errors
- [x] Open Graph tags are working
- [ ] Check Google search result
- [x] Favicon
- [x] 404 page
- [x] Loader
- [x] Website behaves correctly when deleting cookies
- [ ] Analytics has been set up
- [ ] Copyright is in and up-to-date

Design
- [x] Navigation — Does it match what was approved?
- [x] Footer — Does it match what was approved?
- [x] Homepage — Does it match what was approved?
- [x] Subpages — Does it match what was approved?
- [x] Default Page — Does it match what was approved?

Type

- [ ] Typefaces are loaded and displayed correctly
- [x] Fallback typefaces are correct
- [x] No faux bolds
- [x] No faux italics
- [x] Type sizes are correct (H1, H2, H3, H4, H5, H6, p, ul, ol, li)

Content

Text

- [x] Placeholder text is removed / All pages have content

Images

- [x] Images are loaded correctly
- [x] Images are visible in right dimensions and resolutions
- [x] Images have alt tags
- [x] Images have been optimized

Videos

- [x] Videos have been optimized
- [x] Videos have fallback images
- [x] Autoplay videos work

Audio

- [x] Audio files are working

Browser & Devices

Desktop

- [x] Displays & functions correctly in Firefox (Windows)
- [x] Displays & functions correctly in Firefox (Mac)
- [x] Displays & functions correctly in Chrome (Windows)
- [x] Displays & functions correctly in Chrome (Mac)
- [x] Displays & functions correctly in Safari (Mac)
- [x] Displays & functions correctly in Microsoft Edge/Internet Explorer (Windows)
- [x] Displays & functions correctly on large resolutions

Mobile

- [x] Displays & functions correctly in Safari (iOS – Mobile)
- [ ] Displays & functions correctly in Safari (iOS – iPad)
- [ ] Displays & functions correctly in Chrome (iOS – Mobile)
- [ ] Displays & functions correctly in Chrome (iOS – iPad)
- [x] Displays & functions correctly in Chrome (Android – Mobile)
- [ ] Displays & functions correctly in Chrome (Android – Tablet)

Input Testing
- [x] Filtering works
- [x] Search functionalities work correctly

Forms

- [x] All “optional” and “required” fields are behaving as desired
- [x] Alphanumeric fields can properly handle correct and incorrect data, invalid symbols and characters, and numbers that are negative and out of range
- [x] Character limits and min/max lengths were checked
- [x] Date fields accept proper input
- [x] Send works and the data is stored correctly

Extras
- [x] Plugins / Intercoms / Integrations are working
- [x] Redirect any legacy URLs
- [ ] non-www redirects to www
- [ ] transfer repo
- [ ] re-upload newest font files
- [ ] DNS
